### ISSUE TITLE
OSKAR: very long observation (1000+ hours)

### ISSUE THREAD

**Issue by micbia** [i4Ds/Karabo-Pipeline#134]
Hi,
I was wondering if it's possible to do a long observation (1000+ hours) with OSKAR. In my domain, the signal is weak, and long integrated observations, at least 500 hours, are required to hit the required SNR or sensitivity.

At the moment, I can do only ~6 hours of observation before your FoV is below the horizon. Therefore, I need to stop and restart the next (virtual) "day" with start_time_utc.

If that is the case, one should be able to run several OSKAR observations starting at the same time on different days and then combine the visibilities.

Cheers

**Comment by deiruch** [comment]
Thanks for the use-case.

@rohitcbscient Can you suggest an API for this and discuss it with @kenfus ?

**Comment by deiruch** [comment]
There are two ways to approach this:
A) User specifies what he/she's interested in, we will compute an observation schedule from that, run N simulations and combine (#143) the results.
B) User specifies a list of pointings, start & durations. The list might be specified manually by the user or be generated by a Karabo-provided utility function.

I think I prefer option B), because that gives us more flexibility.

**Comment by micbia** [comment]
I agree that option B) is more practical and, ideally, more user-friendly. I want to point out that for 1000+ hours of observation, the MS will be huge (I expect about ~5TB, maybe even more). In this case, it will be unpractical to manage one singular MS; instead, creating N simulations and combining the visibilities afterwards could be a suitable option.
I wonder if this is already possible to do by combining the binary files visibilities that OSKAR output (the file *.vis)

**Comment by deiruch** [comment]
@rohitcbscient What's your view?

**Comment by rohitcbscient** [comment]
Yes, I agree with option (B) as it mimics the observations done in real telescopes. Option A would be more feasible to do testing and large-scale science cases like EoR or Intensity mapping. So, yes, we can start with option B.

**Comment by rohitcbscient** [comment]
Update: Received a script with observational parameters from @micbia on implementing 1000 hours of observation. The observation required is not of a particular source but for the large-scale features for EoR case.

**Comment by Lukas113** [comment]
@rohitcbscient has implemented a seemingly working method for the long observations. I then made a few, mainly structural, adjustments to make the functionality more flexible and to match the previous interface of the framework (but not entirely due to time constraints, see #196 ). New should be used `ObservationLong` instead of `Observation`, which is just a little bit different than `Observation`.

@rohitcbscient will include a qualitative test `karabo.test.tst_long_observation.test_long_observation` to the output in the unittest. So far, only a seemingly error-free run of the program is tested. After that the branch will get merged with `main`.

I don`t think there is any example code for this yet except for the above mentioned test. Should we create an example Notebook for this?

**Comment by deiruch** [comment]
> I don`t think there is any example code for this yet except for the above mentioned test. Should we create an example Notebook for this?

I don't think that's necessary. However, we should mention it in the documentation.
