### ISSUE TITLE
Setup conda package development framework

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#147]

**Comment by Lukas113** [comment]
To provide an update on this matter: the setup for RASCIL and OSKAR (incl. oskarpy) development package building is almost done in the according "dev" branches. However, The RASCIL test failed due to:
```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0

Your installed version is: 2.31
```

This error I've tested on the docker image (ghcr.io/i4ds/mambabuild-docker:latest) that was used on GitHub Actions (also locally), on my own fresh created virtual environment (Ubuntu 20.04, anaconda venv) and on dain.cscs (SLES 15-SP2) using python 3.8 and 3.9. The command that caused this was the simple conda installation: conda install -y -c i4ds rascil. Also the rascil version did not matter (0.7.0 or 0.5.0).

In addition, I also tried oskarpy (conda install -y -c i4ds oskarpy) installation locally, in the above mentioned docker container and on daint.cscs. The only place where it didn't get a similar error than the one above was on cscs.daint using python3.9. And since the GNU C library provides core functions and other people recommended strongly not to upgrade it, I did not touch the library.

**Comment by Lukas113** [comment]
An update, I tried the above installation using a version uploaded from "conda build" of my own local environment. However, if the build (as it should be) comes from the docker image "ghcr.io/i4ds/mambabuild-docker:latest" using "conda mambabuild" then the rascil installation worked in the docker contrainer (locally and on GitHub actions). However, it still failed on my own local machine (fresh venv) throwing the previous mentioned error. These statements are true for python 3.8 and 3.9.

The same applies for cscs.daint on fresh conda environments with python 3.8 and 3.9. The exact error is:
```
Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.26=0
  - python=3.9 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.26
```

**Comment by Lukas113** [comment]
According to [stackoverflow kenneth-hoste)](https://stackoverflow.com/questions/11107263/how-compatible-are-different-versions-of-glibc) glibc is backward-compatible, not forward-compatible.
- docker image: GLIBC 2.31-13+deb11u2
- localhost: GLIBC 2.31-0ubuntu9.9
- cscs.daint: (GNU libc) 2.26

It seems that the docker image uses the newest glibc version and I suspect that might be the cause of this issue.

**Comment by deiruch** [comment]
Done for RASCIL & OSKAR, will be closed when the versioning of OSKAR is done.
