### ISSUE TITLE
Create a PR to remove the check or just warn in upstream RASCIL

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#178]
Remove the check for missing example files or just warn in upstream RASCIL (create a PR)

_Originally posted by @deiruch in https://github.com/i4Ds/Karabo-Pipeline/issues/142#issuecomment-1278679799_

**Comment by Lukas113** [comment]
I think it is already done (see [RASCIL repository](https://gitlab.com/ska-telescope/external/rascil-main/-/blob/master/rascil/processing_components/util/installation_checks.py)). At least on my laptop I just got the warning. Can someone (@kenfus @fschramka or @rohitcbscient ) confirm this? If yes, we could close this issue.

![image](https://user-images.githubusercontent.com/32157249/206404849-3126dd9e-de73-4873-be0c-bd7d1f567a9c.png)

Reproducible if you either delete the data directory OR import karabo from local repository from a Jupyter Notebook (so that __init__.py doesn't set the environment variable)

**Comment by deiruch** [comment]
Closing. Feel free to reopen if this still is an issue.
