### ISSUE TITLE
Unit Tests for User Docker Images

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#189]
We should have tests to detect when public docker images stop working. At least basic functionality should work.

**Comment by deiruch** [comment]
@Lukas113 What's the current status? I think the images are tested nightly, no?

**Comment by Lukas113** [comment]
No the docker images are not tested at all. The tests failed. I'm not entirely sure if it was because the tests are flaky or if something else was the problem.

The initial setup was a layer during the docker build. This was the easiest way to test the image. I don't think testing nightly is better than testing on build because once an image is build everything is installed and nothing can really change.
