### ISSUE TITLE
`SourceDetectionResult.get_real_position_of_sources()` exists

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#209]
This was requested by Patrick Arlt.

**Comment by Lukas113** [comment]
This issue is closed because the information in the `detected_sources` instance variable of `SourceDetectionResult` is already available and easily accessible. An example of this is (assuming `restored: Image` is available):

`detection_result = SourceDetectionResult.detect_sources_in_image(restored)`
`detection_result.detected_sources[:,[1,2]] # ra, dec`
`detection_result.detected_sources[:,[3,4]] # posX, posY`
