### ISSUE TITLE
`SourceDetectionResult.detect_sources_in_image()` does not fail when no sources are detected.

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#210]
```
Also note that I found out that Karabo wasn’t handling correctly the case where it can’t detect any
source. Indeed when Karabo perform the detection, It then extract the pixel coordinates using
indexes (If I did understand the source code right). But this extraction expects to obtain an array that
is 2-dimesionnal (one list of ‘x’ coordinates and one of ‘y’ coordinates). But when there is no sources
detected, we obtain simply an empty array (represented like so ‘[ ]’) and so it has only 1 dimension.
This causes an ‘IndexError’ error when running the function
‘SourceDetectionResult.detect_sources_in_image()’ and that no source is detected.
```

- Patrick Arlt

**Comment by Lukas113** [comment]
Currently I can't reproduce this issue because all I got was a PyBDSF error (not IndexError) with no sources and I can't see where an IndexError from Karabo could even occur.

However, I've seen some potential improvements in the current API (e.g. `Imager` object is not needed in `detect_sources_in_dirty_image` where the according should belong to the `Image` object itself.).

I'll therefore rewrite `detect_sources_in_dirty_image` and make the according adjustments on `Image`. Afterwards I'll test it against no sources and if there are KaraboErrors I will handle them. However, I think it is best to leave PyBDSF errors as they are and let the user handle them.

**Comment by Lukas113** [comment]
The only case where we directly access the detected sources by indices is in `karabo.sourcedeection.result.SourceDetectionResult.get_pixel_position_of_sources`. But this function is not part of `SourceDetectionResult.detect_sources_in_image`. However, as soon as I've rewritten the api as discussed in the comment above, I'll test it and if it is not as expected (I would expect an empty np.ndarray) I intend to improve it.

**Comment by Lukas113** [comment]
Currently I'm not able to reproduce this issue and therefore have requested the corresponding image from the author of the report.

In addition, as partially mentioned above I've done the following in branch `LG_210_detect_sources_in_image`:

- Removed `detect_sources_in_dirty_image` because too much redundancy with `detect_sources_in_image`, thus is no longer dependent on `Imager`.
- No lazy-loading of header and data from `Image`. So the instance variable is always accessed directly. That means you always know where the information comes from.
- An `Image` is now always loaded from a file when instantiation is performed. That means, the image instance is not only used to get the `file-path` and save something there (like before) but the file has to be saved first, so that an `image` instance can be created.
- `SourceDetectionResult.detect_sources_in_image` catches `bdsf RuntimeError` if all pixels in the image are blanked.
- Bugfix when just a single source is present for `SourceDetectionResult.detect_sources_in_image` and `sky.explore_sky`.
- Adapted according interfaces and tests
