### ISSUE TITLE
The axes of the plot `telescope.plot_telescope()` are labelled.

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#223]
Currently, the plot contains no labels and it should have labels. 
Feedback was given by Jennifer Studer.

**Comment by jejestern** [comment]
From where do you have the position information of the MeerKAT telescope saved in the folder meerkat.tm? They seem to be slightly wrong. According to https://skaafrica.atlassian.net/servicedesk/customer/portal/1/article/277315585 the location should be (21.444, -30.711) degrees instead of (20.411, -30.721) degrees.
