### ISSUE TITLE
Allow Karabo user to compile certain packages from source

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#265]
Spack apparently allows very clean python classes, containing the information on how to build and install python packages: https://spack.readthedocs.io/en/latest/packaging_guide.html

I don't think this is needed now because our slowest steps are currently CUDA-steps, which apparently does not gain much (nothing) by compiling it on your machine from source. However, maybe in the future we find code which would profit a lot from compiling on from source on your machine. 

We could add it similar to how Intel patches scikit-learn to profit from the AVX-architecture:
```
from sklearnex import patch_sklearn
patch_sklearn()
```

So this would mean something like this:

```
from karabo.utils.patching import patch_pinocchio
patch_pinocchio()
```

**Comment by deiruch** [comment]
Victor Holanda said in the past he'd support such activities.

**Comment by deiruch** [comment]
Btw: We took a conscious decision to provide pre-built binaries, instead of compiling on user machines. The reasons are complexity and usability.

So far we haven't seen noticed real-world cases where we lose a lot of performance because of this. Feel free to reopen when we found an actual case. I think we should then discuss how to tackle that specific problem. (IMHO, there are usually better ways than compiling on users machines.)
