### ISSUE TITLE
Documentation explains what users can do with measurement sets

### ISSUE THREAD

**Issue by ACsillaghy** [i4Ds/Karabo-Pipeline#351]
Once I have generated a measurement set with the simulator, what can I do with it?

**Comment by deiruch** [comment]
@Lukas113 will focus on better documentation to ensure a softer landing for first-time users. The documentation should explain what you can do with MSs.

**Comment by Lukas113** [comment]
The short answer is, you can use it to create a `Visibility` object and do whathever Karabo allows to do with it.

However, this issue is closed because firstly it is already written in the docstrings of the according objects & functions, and secondly, it should get more elaborated once #304 is done, which makes this issue redundant.
