### ISSUE TITLE
Update `ObservationLong`

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#390]
While timing and working on the parallelization for OSKAR, I found some things which seems to be technical debt and cause problems:

- `ObservationLong `creates a popup-Window, if you want to overwrite old files. This should go
- class `FileHandle `and `Visibility `has in different functions things like "if exist, remove". Those should also go or just overwrite automatically. Some files are already repeadiblity written and overwritten. Example: `beam_vis_1.ms`
- `ObservationLong `should make use of lists and pd.date_range to iterate trough visiblities and dateranges.

**Comment by Lukas113** [comment]
@kenfus 

- Agree on the popup-window
- Also agree that something should change, but not quiet sure what exactly. I think it makes sense to not overwrite existing end-product files automatically unless you set an `overwrite` flag, especially for something that could take some time and resources. And in case if you don't overwrite, you may want to resume an already existing simulation. However, I think some "if exist, remove" behavior should be checked in the according user-api function through a package-wide consistent keyword. Otherwise you could have some unexpected behavior I think. I am just not a fan of overwriting already existing end-product files unless you really want to.
- Not quiet sure why it should iterate through pd.data_range. Can you explain why?

**Comment by kenfus** [comment]
> * Agree on the popup-window
> * Also agree that something should change, but not quiet sure what exactly. I think it makes sense to not overwrite existing end-product files automatically unless you set an `overwrite` flag, especially for something that could take some time and resources. And in case if you don't overwrite, you may want to resume an already existing simulation. However, I think some "if exist, remove" behavior should be checked in the according user-api function through a package-wide consistent keyword. Otherwise you could have some unexpected behavior I think. I am just not a fan of overwriting already existing end-product files unless you really want to.
This was discussed with @deiruch. You can pass now a folder where you want to save the intermediate steps. Technically, you can go and check them. The end result is overwritten, if the new combined visibility is written to the same place (paramter `path` is the same). 
> * Not quiet sure why it should iterate through pd.data_range. Can you explain why?
Cleaner and less code, less logic.

**Comment by Lukas113** [comment]
> This was discussed with @deiruch. You can pass now a folder where you want to save the intermediate steps. Technically, you can go and check them and they are not automatically overwritten because they use a uuid (with the FileHandle class). The end result is overwritten, if the new combined visibility is written to the same place (paramter path is the same).

The solution with an uuid is looking good I think. But I think there is an error with `clean_up`. This method is an object method, but you use `rmtree` on `__temp_path` which is a class, not an object variable. I think either you want to `rmtree` `tmp_path` and not `FlieHandle.__temp_path` OR you want to write `clean_up` as a static method if you really intend to `rmtree` `FileHandle.__temp_path` because `FileHandle.__temp_path` is static.

> Cleaner and less code, less logic.
Why should it be cleaner and less code than `for i in range(observation.number_of_days):` ?

**Comment by kenfus** [comment]
> > This was discussed with @deiruch. You can pass now a folder where you want to save the intermediate steps. Technically, you can go and check them and they are not automatically overwritten because they use a uuid (with the FileHandle class). The end result is overwritten, if the new combined visibility is written to the same place (paramter path is the same).
> 
> The solution with an uuid is looking good I think. But I think there is an error with `clean_up`. This method is an object method, but you use `rmtree` on `__temp_path` which is a class, not an object variable. I think either you want to `rmtree` `tmp_path` and not `FlieHandle.__temp_path` OR you want to write `clean_up` as a static method if you really intend to `rmtree` `FileHandle.__temp_path` because `FileHandle.__temp_path` is static.
I am unsure what you mean but in my PR it's `rmtree(self.path)`. I think the __temp_path never made sense, right?
> 
> > Cleaner and less code, less logic.
> 
> Why should it be cleaner and less code than `for i in range(observation.number_of_days):` ?
Well, you need to pass the datetime object to oskar, so you need to create the datetime object first every loop. With date_range it's already done! :D

**Comment by Lukas113** [comment]
> I am unsure what you mean but in my PR it's rmtree(self.path). I think the __temp_path never made sense, right?

I was on `main`, not on [Vt 383 run simulation runs on multiple nodes](https://github.com/i4Ds/Karabo-Pipeline/pull/386/files#top), my bad

> Well, you need to pass the datetime object to oskar, so you need to create the datetime object first every loop. With date_range it's already done! :D

Well, sure. This should also fix the error I've just seent:  `current_date` doesn't update (variable assignment is missing)..

**Comment by Lukas113** [comment]
@kenfus  This is solved with PR #386  right? If yes, please close.

**Comment by kenfus** [comment]
Closed with PR #386
