### ISSUE TITLE
Bundle Bluebild/BIPP with Karabo

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#427]
https://github.com/epfl-radio-astro/bipp should be bundled with Karabo.

**Comment by fschramka** [comment]
need to create a conda package of the finufft dependency first :)

**Comment by fschramka** [comment]
Finufft packages created for python 3.9 & 3.10. Included are also the native binaries (release 2.1.0) - CUDA is not included in this latest release. 
https://anaconda.org/i4Ds/finufft/files

Bluebild (bipp) is also rdy for python 3.9 & 3.10:
https://anaconda.org/i4Ds/bluebild/files

--> version was set to 1.0.0 because there was no official release version :)
