### ISSUE TITLE
Document ALMA antenna configuration

### ISSUE THREAD

**Issue by cvoegele** [i4Ds/Karabo-Pipeline#46]
The ALMA configuration should not have this many antennas. This needs fixing.

**Comment by deiruch** [comment]
[Devin Crichton](https://app.slack.com/team/U02PETQ9P0B) [Today at 3:13 PM](https://swissska.slack.com/archives/C02M54N7WDR/p1645798413169099)
Regarding the presentation, why does ALMA have antennas and stations?
12 replies

[Marc Audard](https://app.slack.com/team/U019KF8RX4G)  [2 hours ago](https://swissska.slack.com/archives/C02M54N7WDR/p1645798519634529?thread_ts=1645798413.169099&cid=C02M54N7WDR)
If I may intervene here, perhaps to help, not sure I understand the question.

[Rohit Sharma](https://app.slack.com/team/U01GCD07TLH)  [2 hours ago](https://swissska.slack.com/archives/C02M54N7WDR/p1645798582709189?thread_ts=1645798413.169099&cid=C02M54N7WDR)
Yes, that is one issue we need to sort it out. So, there is only one station.

[Marc Audard](https://app.slack.com/team/U019KF8RX4G)  [2 hours ago](https://swissska.slack.com/archives/C02M54N7WDR/p1645798642806059?thread_ts=1645798413.169099&cid=C02M54N7WDR)
OK, as I am not involved I may not catch the issue. ALMA has many antennas with many stations, with the goal of having different configurations.

[Devin Crichton](https://app.slack.com/team/U02PETQ9P0B)  [2 hours ago](https://swissska.slack.com/archives/C02M54N7WDR/p1645798686927849?thread_ts=1645798413.169099&cid=C02M54N7WDR)
To clarify the question, it looks like ALMA is being simulated like an SKA-low-like system but with the ALMA array layout for stations.

[Mark Sargent](https://app.slack.com/team/U02P5R6V0TC)  [1 hour ago](https://swissska.slack.com/archives/C02M54N7WDR/p1645798721355259?thread_ts=1645798413.169099&cid=C02M54N7WDR)
Stations = antenna foundations (there are 192 of them, which can accommodate the 66 antennae in a range of different configurations)
:+1:
1


[Devin Crichton](https://app.slack.com/team/U02PETQ9P0B)  [1 hour ago](https://swissska.slack.com/archives/C02M54N7WDR/p1645798774703039?thread_ts=1645798413.169099&cid=C02M54N7WDR)
Yeah, but the image had the orange points as stations with many blue antennas per if I saw correctly.

[Mark Sargent](https://app.slack.com/team/U02P5R6V0TC)  [1 hour ago](https://swissska.slack.com/archives/C02M54N7WDR/p1645798848416939?thread_ts=1645798413.169099&cid=C02M54N7WDR)
Would you be able to post the image here?

[Christoph Vögele](https://app.slack.com/team/U02751607J5)  [1 hour ago](https://swissska.slack.com/archives/C02M54N7WDR/p1645798961718619?thread_ts=1645798413.169099&cid=C02M54N7WDR)[](https://files.slack.com/files-pri/T017Z95GELQ-F03491GF4MV/alma.png)[](https://files.slack.com/files-pri/T017Z95GELQ-F03491GF4MV/download/alma.png)
Of course. I have the image here. It may very well be it needs fixing.
alma.png 
alma.png



[Rohit Sharma](https://app.slack.com/team/U01GCD07TLH)  [1 hour ago](https://swissska.slack.com/archives/C02M54N7WDR/p1645798979765489?thread_ts=1645798413.169099&cid=C02M54N7WDR)
Yes Devin, at the moment the implementation of a dish is equivalent to a station with one antenna with modified beams. (edited) 

[Devin Crichton](https://app.slack.com/team/U02PETQ9P0B)  [1 hour ago](https://swissska.slack.com/archives/C02M54N7WDR/p1645799105082679?thread_ts=1645798413.169099&cid=C02M54N7WDR)
Ok, so that's not a grid of antennas per station, just one.

[Devin Crichton](https://app.slack.com/team/U02PETQ9P0B)  [1 hour ago](https://swissska.slack.com/archives/C02M54N7WDR/p1645799170893049?thread_ts=1645798413.169099&cid=C02M54N7WDR)
(Sorry I think there is some overlapping terminology here, I assumed the SKA-low terms since OSKAR is being used)

[Rohit Sharma](https://app.slack.com/team/U01GCD07TLH)  [1 hour ago](https://swissska.slack.com/archives/C02M54N7WDR/p1645799266641149?thread_ts=1645798413.169099&cid=C02M54N7WDR)
The terminology is explained here: https://ska-telescope.gitlab.io/sim/oskar/telescope_model/telescope_model.html

**Comment by deiruch** [comment]
We can clarify this in the documentation.

**Comment by deiruch** [comment]
@rohitcbscient any updates on this?

**Comment by rohitcbscient** [comment]
The documentation needs to be updated. Not done yet.

**Comment by deiruch** [comment]
Manual is here https://i4ds.github.io/Karabo-Pipeline/development.html#update-documentation

**Comment by rohitcbscient** [comment]
A brief readme for telescope directory structure is added.
