### ISSUE TITLE
Move datasets from Nextcloud to CSCS

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#88]

**Comment by cvoegele** [comment]
Update from Victor.:
 
In order to avoid authenticating, one needs to use FirecREST (https://products.cscs.ch/firecrest/), which requires its machinery set… (edited) 
[9:33](https://swissska.slack.com/archives/D03EYM63M35/p1654846386001899)
There is no way that one can copy files without authentication. What FirecREST does for you is: it holds your authentication on your behalf for a given amount of time. But you have to authenticate to FirecREST, in the first place…
white_check_mark
eyes
raised_hands

[9:33](https://swissska.slack.com/archives/D03EYM63M35/p1654846427840149)
Please read the page, and tell me if you are interested in using it. I can set up a meeting with the developers and they explain to you more in details how to use it and what you need to do to do use it…

**Comment by deiruch** [comment]
Ok, I managed to set it up, the following way:

1. Read https://github.com/eth-cscs/openstack/tree/master/cli
1. `source openstack/cli/castor.env`
1. `swift post karabo_public --read-acl ".r:*,.rlistings"`
1. `swift upload karabo_public example_file.fits`

After this, everyone can access `example_file.fits` via https://object.cscs.ch/v1/AUTH_1e1ed97536cf4e8f9e214c7ca2700d62/karabo_public/example_file.fits

@rohitcbscient @cvoegele What files should I move there?

**Comment by deiruch** [comment]
9749844c0df9081b5c6f50eb080ffb721fa8173e uses CSCS URLs now. Documentation not yet completed.
